package io.labyrinth.bot.guilded.util

internal class InternalFailureException(message: String): RuntimeException(message)